### ISSUE TITLE
wds this project in the form of screenshots

### ISSUE THREAD

**Issue by Zva777** [michaelpearson/HC-12-transmitter#1]
Hello. Whether probably to receive from you a configuration wds this project in the form of screenshots. I wish to try to reduce speed of transfer and deviation for reception of the maximal range. It is very necessary.

**Comment by michaelpearson** [comment]
It has been a long time since I worked on this project. However, it should be possible to open the project in the wireless configuration tool. The repository contains the project file that I used.
